### PR TITLE
chore:(decimal): add decimal type and check #1

### PR DESCRIPTION
**Pull request by developerfred**
I added the type: decimal and now every time the _**getBalanceNumber**_ function is called it will take into account the decimal places of the token, this solves your problem.

### CODE REVIEW

**Comment by Gajesh2007** [comment]
Hi Fred,

While testing the code on my computer, it didn't work

**Comment by Gajesh2007** [comment]
Hi Fred, 

The balance is working fine but the reward is showing wrong

Also, there is bug while unstaking and staking 
Screenshot 2021-05-06 at 5 30 38 PM

Screenshot 2021-05-06 at 5 29 44 PM

**Comment by developerfred** [comment]
> Hi Fred,
> 
> The balance is working fine but the reward is showing wrong
> 
> Also, there is bug while unstaking and staking

try now, I add arguments on stake and unstack

**Comment by Gajesh2007** [comment]
Btw, @developerfred I would like to hire you for this project. Would you like to work with us?

**Comment by Gajesh2007** [comment]
Below error is getting displayed:

Failed to compile.

src/hooks/useStake.ts
  Line 19:5:  React Hook useCallback has a missing dependency: 'decimal'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/hooks/useUnstake.ts
  Line 24:5:  React Hook useCallback has a missing dependency: 'decimal'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each error.

**Comment by developerfred** [comment]
check now @Gajesh2007

**Comment by Gajesh2007** [comment]
it's not working

**Pull request closed without merging**
